% Check if required files from NLvib are available on the path
tmp = [ ...
    exist('MechanicalSystem.m','file') ...
    exist('FE_EulerBernoulliBeam.m','file') ...
    exist('CMS_ROM.m','file') ...
    exist('HB_residual.m','file') ...
    exist('solve_and_continue.m','file') ...
    ];
if any(tmp~=2)
    error(['Required NLvib files not found on search path. ' ...
        'Please download recent NLvib version from https://github.com/maltekrack/NLvib/. ' ...
        'Extract it in a (arbitrary sub-)folder within the SRC folder ' ...
        '(subfolders of SRC will automatically be added to the search path), ' ...
        'or extract it anywhere else and extend the search path accordingly.']);
end